version: '3'
services:
  azure-function:
    build: ./azure
    ports:
      - "7071:80"
    env_file:
      - ./.azure.env
    volumes:
      - ./etc/test-secrets:/azure-functions-host/Secrets
  server:
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./.server.env